sudo: required

language: go

go:
  - 1.11.4
  - 1.12.x

services:
  - docker

install:
  - for i in $(seq 1 5); do (dep ensure && break) || sleep 30; done # Install dependencies listed in the go.mod and go.sum files.

env:
  - PATH=$HOME/protoc/bin:$PATH

script:
  - make unit-test integration

after_success:
  - bash <(curl -s https://codecov.io/bash)
