{{- range $i, $e := until (int .Values.num_trackers) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-origin-{{$i}}
  labels:
    kraken: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      kraken-app: origin-{{$i}}
  template:
    metadata:
      labels:
        kraken: 'true'
        kraken-app: origin-{{$i}}
        kraken-peer: 'true'
    spec:
      containers:
      - name: main
        image: gcr.io/uber-container-tools/kraken-origin:v0.1.1
        command:
        - /usr/bin/kraken-origin
        - --config=/etc/config/origin.yaml
        - --blobserver-hostname=kraken-origin-0
        - --blobserver-port=80
        - --peer-port=8080
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: kraken
---
kind: Service
apiVersion: v1
metadata:
  name: kraken-origin-{{$i}}
  labels:
    kraken: 'true'
spec:
  selector:
    kraken-app: origin-{{$i}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{- end -}}
