---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-proxy
  labels:
    kraken: 'true'
spec:
  replicas: {{ .Values.num_proxies }}
  selector:
    matchLabels:
      kraken-app: proxy
  template:
    metadata:
      labels:
        kraken: 'true'
        kraken-app: proxy
    spec:
      containers:
      - name: main
        image: gcr.io/uber-container-tools/kraken-proxy:v0.1.1
        command:
        - /usr/bin/kraken-proxy
        - --config=/etc/config/proxy.yaml
        - --port=80
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: kraken
---
kind: Service
apiVersion: v1
metadata:
  name: kraken-proxy
  labels:
    kraken: 'true'
spec:
  selector:
    kraken-app: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
