apiVersion: v2
name: kraken
description: P2P Docker registry capable of distributing TBs of data in seconds
type: application
version: 0.1.19
appVersion: "0.1.19"
kubeVersion: ">=1.19.0"
keywords:
  - http
  - docker
  - registry
  - p2p
  - container
  - image
home: https://github.com/uber/kraken
sources:
  - https://github.com/uber/kraken
maintainers:
  - name: Kraken Maintainers
    url: https://github.com/uber/kraken
