extends: base.yaml

backends:
  - namespace: library/.*
    backend:
      registry_tag:
        address: index.docker.io
        security:
          basic:
            username: ""
            password: ""
  - namespace: .*
    backend:
      testfs:
        addr: host.docker.internal:14000
        root: tags
        name_path: docker_tag

cluster:
  hosts:
    static:
      - host.docker.internal:15004

origin:
  hosts:
    static:
      - host.docker.internal:15002

remotes: {}

tag_replication:
  retry_interval: 100ms
  poll_retries_interval: 250ms

tag_types:
  - namespace: .*
    type: docker
    root: tags

tag_store:
  write_through: false

writeback:
  retry_interval: 100ms
  poll_retries_interval: 250ms

nginx:
  cache_dir: /tmp/kraken-build-index-nginx/

tls:
  name: kraken
  cas:
  - path: /etc/kraken/tls/ca/server.crt
  server:
    cert:
      path: /etc/kraken/tls/ca/server.crt
    key:
      path: /etc/kraken/tls/ca/server.key
    passphrase:
      path: /etc/kraken/tls/ca/passphrase
  client:
    cert:
      path: /etc/kraken/tls/client/client.crt
    key:
      path: /etc/kraken/tls/client/client.key
    passphrase:
      path: /etc/kraken/tls/client/passphrase
